;; ##nobackup##
;; ##nofindgrep##
(ff "\\b[a-h]:")
(ff "emacs-lisp-dir")
(ff "locate")
(ff "bash")
(ff "/white/i")
(ff "egham")
(ff "88")
(ff "/jam/i")
(ff "pixel")
(ff "default-frame-alist")
(ff "cygwin")
(ff "server")
(ff "cygwin")
(ff "qb-define")
(ff "qb-and-mini")
(ff "minibuffer-dir")
(ff "dev")
(ff "devhome")
(ff "gud|gdb")
(ff "mouse")
(ff "\\bhome\\b")
(ff "advice")
(ff "daily")
(ff "today")
(ff "panic")
(ff "key")
(ff "ns-")
(ff "cut")
(ff "printer-name")
(ff "compil.*reg")
(ff "hook")
(ff "INC")
(ff "diff")
(ff "version")
(ff "find-file")
(ff "x-get")
(ffe "define-key.*global-map")
(ffe "face")
(defun foo () (interactive) (insert (x-selection)))
(define-key global-map "\C-z." 'foo)

(dotimes (i 20)
;  (insert "(devil) (puke) (h)")
  (insert "(talk)")
)
(ff "history")
(ffe "bob")
(ff "nl-exec")
(ff "\\bc-"  "\\.el$")

(ff "visit.log")

(ff "PATH")
(ff "path-add")

(ebgp "strftime")
(ebgp "stat")
(ebg "/drive/i")
(ebg "/monkey/i")

(ebg "mp3" "--fpat=\\.nl$")
(ebg "wav-split" "--fpat=\\.nl$")

(ebg "exec"  "--fpat=\\.nl$")

(ebg "match"  "--fpat=\\.nl$")

(ebgp "HTTP")
(ebgp "http://")
(ebgp "m!/fly!")

(ebg "#>wav" "\\.nl$")
(ebg "wav-append")
(ebg "wav-file-save")
(ebg "wav-" "\\.nl$")
(ebg "with-output" "--fpat=\\.nl$")
(ebg "open file" "--fpat=\\.nl$")
(ebg "festival"  "--fpat=\\.[pn][lm]$")

(ebg "1251")
(ebg "coding")
(ebg "perl-process")

;##noid##
(ff "##id##")
(ff "substring")
(ff "PATH")

(ff "gdb-quick")
(ff "lock-buffer")
(apropos "dedicated")

(ff "other-window")
(ff "system")

(ff "emacs-2")
(ff "loading-path")
(ff "override")

(ff "backup-root")
(ff "emacs-exec-dir")
(ff "get-buffer-window-any-frame")

(ff "/\\b[a-z]:/i")
(ff "ls-lisp")

(ff "font")
(ff "register")

(ff "string-parse")
(ff "speedbar")
(ff "history")
(ff "read-from-minibuffer")
(ff "-path")
(ff "org")
(ff "vom-path")

(ff "vom")
(ff "kill-current-buffer")
(ff "kill-ring")
(ff "filename-concat")
(ff "keys")
(ff "php-exe")
(ff "yas")
(ff "dev-path")
(ff "loading")

(ff "compile")
(ff "string-sub")
(ff "monotype-Courier")
(ff "perl")
(ff "scroll-bar")
(ff "time")
(ff "dbg-mode")
(ff "advice")

(ff "devhome")
(ff "wcc")
(ff "org")

(ff "backup-root")

(ff "vom-")
(ff "home-daily-root")

(ff "system-info-directory")
(ff "f11")
(ff "bash")
(ff "devhome")

(ff "setenv")

(ff "vom")
(ff "load-path")
(ff "emacs-home")
(ff "command-history")

(ff "list-split-insert")
(ff "\\bg[ud].*hook")

(ff "history")
(ff "interactive ")

(ff "property")
(ff "w32")
(ff "command-history-save")
(ff "modifier")

(ff "m!e:/!")
(ff "php")
(ff "replace.el")

(ff " suffix")
(ff "standard-load-path")
