initial-frame-alist
(height . 87)
(top . 1)
(left . 160)
(background-color . LightGray)
(menu-bar-lines . 0)
(tool-bar-lines . 0)


(setq default-frame-alist
  `(
    (height . 87)
    (top . 1)
    (left . 800)
    (background-color . "LightGray")
    (menu-bar-lines . 0)
    (tool-bar-lines . 0)
    (scroll-bar-width . 12)
    )
  )

(setq scroll-bar-mode 'right)
(set-scroll-bar-mode 'right)

(parent-id . 38427029)
(explicit-name)
(display . :0.0)
(visibility . t)
(icon-name)
(outer-window-id . 62914720)
(window-id . 62914748)
(top . 26)
(left . 27)
(buried-buffer-list frame-initial.el)
(buffer-list frame.el .emacs  *Minibuf-1* shell-0 start.el *scratch*)
(unsplittable)
(minibuffer . #<window 4 on  *Minibuf-0*>)
(modeline . t)
(width . 80)
(height . 54)
(name . frame.el)
(environment)
(fullscreen)
(background-mode . light)
(display-type . color)
(horizontal-scroll-bars . t)
(window-system . x)
(alpha)
(scroll-bar-width . 16)
(cursor-type . box)
(auto-lower)
(auto-raise)
(icon-type . t)
(wait-for-wm . t)
(title)
(buffer-predicate)
(tool-bar-lines . 0)
(menu-bar-lines . 0)
(scroll-bar-background . grey75)
(scroll-bar-foreground)
(right-fringe . 8)
(left-fringe . 8)
(line-spacing)
(screen-gamma)
(border-color . black)
(cursor-color . black)
(mouse-color . black)
(background-color . LightGray)
(foreground-color . black)
(vertical-scroll-bars . right)
(internal-border-width . 0)
(border-width . 2)
(font . -b&h-Lucida Console-normal-normal-semi-condensed-*-13-*-*-*-m-0-iso10646-1)
(font-backend xft x)

(menu-bar-lines . 0)
(scroll-bar-background . grey75)
(scroll-bar-foreground)
(right-fringe . 8)
(left-fringe . 8)
(line-spacing)
(screen-gamma)
(border-color . black)
(cursor-color . black)
(mouse-color . black)
(background-color . LightGray)
(foreground-color . black)
(vertical-scroll-bars . left)
(internal-border-width . 0)
(border-width . 2)
(font . -b&h-Lucida Console-normal-normal-semi-condensed-*-13-*-*-*-m-0-iso10646-1)
(font-backend xft x)


(ff "scroll" nil "/usr/share/emacs/23.1/lisp")
