(defun confirm (&optional msg)
  (message (or msg "Confirm: "))
  (let ((char (read-char)))
    (cond
     ((or (= char ?\e)
	  (= char ?q))
      (throw 'done t))
     ((= char ?d) (debug) t)
     ((= char ?!) (setq noconfirm t))
     ((or (= char ?\ )
	  (= char ?y))
      t)
     ((or (= char ?\177)
	  (= char ?n))
      nil)
     ((= char ?\C-r)
      (save-excursion (recursive-edit))
      (confirm msg))
     )))

