(setq eval-text-before-hook nil)
(setq eval-text-after-hook nil)

(defun eval-text-buffer () (interactive)
  (let* ((buf (current-buffer))
	 (string (buffer-string))
	 (new (get-buffer-create "*show*"))
	 )
    (display-buffer (set-buffer new))
    (erase-buffer)
    (insert string)
    (bob)
    (run-hooks 'eval-text-before-hook)
    (sx
     (while (rsf "#" nil t)
       (let* ((s (- (point) 1))
	      (exp (eval (read (current-buffer))))
	      (e (+ (point) 1)))
	 (delete-region s e)
	 (sx (and (stringp exp) (insert exp)))
	 )))
    (sx
     (while (rsf "\\\\$" nil t) (fc -1) (dc 2)))
    (run-hooks 'eval-text-after-hook)
    ))
