(defun repexp (exp &optional new i)
  (setq i (or i 0))
  (cond ((rsf exp nil t)
	 (kill-region (match-beginning i) (match-end i))
	 (and new (insert new))
	 )))

(defun fix-in ()
  (repexp "yytext\\[]" "*yytext")
  (repexp "yysbuf\\[]" "*yysbuf")
  (repexp "^yylex()" "_yylex()")
  (repexp "^char yytext\\[YYLMAX];" "char *yytext ;")
  (repexp "yylstate \\[YYLMAX]" "*yylstate")
  (repexp "^char yysbuf\\[YYLMAX]" "char *yysbuf")
  (repexp " = yysbuf")
  )

(let* ((list (buffer-list))
       (in (nth 1 list))
       (out (nth 0 list))
       )
  (set-buffer in)
  (fix-in)
  (write-file (buffer-file-name out))
  )

