(defun nload-file (f)
  (let* ((name (generate-new-buffer-name " *nload*"))
	 (buffer (get-buffer-create name))
	 )
    (set-buffer buffer)
    (insert-file-contents f)
    (remove-block-comments-for-load)
    (set-buffer-modified-p nil)
    (eval-buffer buffer)
    (kill-buffer buffer)
    )
  )

(defun remove-block-comments-for-load ()
  (beginning-of-buffer)
  (while (search-forward "#|" nil t)
    (let ((start (- (point) 2))
	  (end (search-forward "|#" nil t))
	  )
      (delete-region start end)
      )
    )
  )

