(setq ps-shell "d:/A/Adobe/Acrobat 7.0/Distillr/acrodist.exe")

(defun ps-eval-buffer () (interactive)
  (save-buffer)
;  (call-shell (format "\"%s\" /N /Q %s" ps-shell (buffer-file-name)))
;  (call-process (format "%s /N /Q %s" ps-shell (buffer-file-name)))
;  (start-process "ps" "ps" ps-shell "/N" "/Q" (buffer-file-name))
  (start-process "ps" "ps" ps-shell (buffer-file-name))
  )

(defun ps-eval-buffer () (interactive)
  (save-buffer)
;  (call-shell (format "\"%s\" /N /Q %s" ps-shell (buffer-file-name)))
;  (start-process "ps" "ps" ps-shell "/N" "/Q" (buffer-file-name))
;  (start-process "ps" "ps" ps-shell (buffer-file-name))
  (call-process ps-shell nil nil t "/N" "/Q" (buffer-file-name))
  (let* ((log (format "%s.log" (basename)))
	 (buf (get-buffer log)))
    (cond (buf (kill-buffer buf)))
    (find-file-other-window log)
    )
  )

(defun ps-mode () (interactive)
  (setq mode-name "ps")
  (setq major-mode 'ps-mode)
  (use-local-map ps-mode-map)
  )
