(defun highlight-trailing-whitespace ()
  (interactive)
  (let ()
    (sx
     (bob)
     (while (rsf ".*?\\([ \t]+\\)$")
       (let* ((s (match-beginning 1))
	      (e (match-end 1))
	      (ov (make-overlay  s e nil t)))
;      (message "%s %s" s e)
	 (overlay-put ov 'face 'magit-diff-whitespace-warning)
	 (overlay-put ov 'priority 2)
;	 (overlay-put ov 'after-string ">")
;	 (overlay-put ov 'before-string "<")
	 )
       )
     )
    )
  )

(defun buffer-registers-highlight-remove ()
  (interactive)
  (let* ((lists (overlay-lists))
	 (list (apply 'append lists))
	 )
    (dolist (o list)
      (cond ((eq (plist-get (overlay-properties o) 'use) 'register-highlight)
	     (delete-overlay o)
	     )
	    )
      )
    )
  )

(defun buffer-registers-highlight ()
  (interactive)
  (buffer-registers-highlight-remove)
  (let ((list register-alist))
    (sx

     (dolist (i list)
       (let* ((tag (car i))
	      (marker (cdr i))
	      (buffer (marker-buffer marker))
	      (pos (marker-position marker))
	      (face 'magit-diff-whitespace-warning)
	      ov
	      )
	 (cond ((eq buffer (current-buffer))
		(setq ov (make-overlay pos pos nil nil nil))
		(overlay-put ov 'priority 2)
;		(overlay-put ov 'before-string (propertize (format "<%c>" tag) 'face face))
		(overlay-put ov 'before-string (concat (propertize "<<" 'face face)
						       (format "%c" tag)
						       (propertize ">>" 'face face)
						       ))
;		(overlay-put ov 'after-string (propertize (format "<%c>" tag) 'face face))
		(overlay-put ov 'use 'register-highlight)
		(overlay-put ov 'face face)
		))
	 )
       )
     )
    )
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defun indent-to-column-rigid (col)
  (just-one-space)
  (indent-to-column col)
  )

(defun indent-pattern-to-column (pat col &optional noquery)
  (interactive "sPattern: \nPColumn: ")
  (let (start end (map query-replace-map))
    (cond ((region-active-p)
	   (setq start (region-beginning))
	   (setq end (set-marker (make-marker) (region-end)))
	   column
	   )
	  ((setq start (point)) (setq end (point-max-marker)))
	  )
    (or col (setq col goal-column) (setq col (current-column)))
    (save-excursion
      (goto-char start)
      (while (and (< (point) end) (rsf pat end nil nil t))
	(setq column (cond ((symbolp col) (funcall col)) (col)))
	(cond (noquery (setq def 'act))
	      ((message "indent to column %s? " column)
	       (setq key (read-event))
	       (setq def (lookup-key map (vector key)))
	       )
	      )
	(cond
	 ((eq def 'skip) (end-of-line))
	 ((eq def 'act) (indent-to-column-rigid column) (end-of-line))
	 ((eq def 'automatic) (indent-to-column-rigid column) (setq noquery t))
	 ((eq def 'exit) (eob))
	 ((eq def 'recenter) (recenter))
	 ((eq def 'backup) (rsb pat start nil nil t) (bol) )
	 ((funcall def))
	 )
	)
      )
    )
  )

;(global-set-key (kbd "M-s M-i") 'indent-pattern-to-column)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defun occur-dwim ()
  "Call `occur' with a sane default."
  (interactive)
  (push (if (region-active-p)
            (buffer-substring-no-properties
             (region-beginning)
             (region-end))
          (let ((sym (thing-at-point 'symbol)))
            (when (stringp sym)
              (regexp-quote sym))))
        regexp-history)
  (call-interactively 'occur))

;(global-set-key (kbd "M-s M-=") 'occur-dwim)


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defun split-this-buffer-window (arg)
  (interactive "P")
  (delete-other-windows)
  (split-window-below)
  )

;(define-key c-z-map (kbd "C--") 'split-this-buffer-window)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(bulkload-directory (filename-concat user-emacs-home "recent/2103"))

