(defun replace-thing-at-point-fun (thing fun)
  (let* ((it (thing-at-point thing))
	 (bounds (bounds-of-thing-at-point thing))
	 (new (funcall fun it))
	 )
    (kill-region (car bounds) (cdr bounds))
    (insert new)
    )
  )
