#+CLASS: help manual notes
#+DESCRIPTION: growlnotify posts a notification which can be made visible on-screen
#+TOPIC: growl
* growlnotify
  there's a unix-style one that takes hyphen style parameters
  and a dos-style one that takes slash style parameters

  https://www.autohotkey.com/board/topic/122719-using-autohotkey-with-growl-for-windows-via-growlnotify/
  
** unix style man page (man  1 grow -w e:/emacs/.try/grow.1)
GROWLNOTIFY(1)            BSD General Commands Manual           GROWLNOTIFY(1)

NAME
     growlnotify -- send a notification to Growl

SYNOPSIS
     growlnotify [-hsvuwc] [-i ext] [-I filepath] [--image filepath]
                 [-a appname] [-p priority] [-H host] [-P password] [-n name]
                 [-A method] [-m message] [-t] [title]

DESCRIPTION
     growlnotify posts a notification using GNTP to Growl, or other GNTP en-
     abled listeners, such as Growl for Windows.

     The options are as follows:

     -h, --help  Display this help and exit.

     -v, --version
                 Display version number and exit.

     -n, --name name
                 Sets the application name to register the notification under.
                 By default 'growlnotify' is used.

     title       The title of the notification.

     -t, --title
                 Does nothing.  This is included to make the syntax compatible
                 with gnotify, another Growl example written in a different
                 programming language.

     -m, --message message
                 Uses message instead of stdin as the notification message
                 (also called description).  If message is '-', stdin is still
                 used.

     -a, --appIcon name
                 Sets the notification's application icon to the icon for the
                 given application name. If you don't specify a notification
                 icon, this will be used instead of it; if you specify both,
                 the application icon may be used as a badge (that is, dis-
                 played in a corner of the notification icon, superimposed on
                 top of it), or the display may show both separately.  Icons
                 are not supported by all displays, so this may be ignored.

     -i, --icon ext
                 Sets the notification icon to the default icon for the given
                 extension or HFS-encoded file type. For example, -i mp3 and
                 -i 'MP3 ' (note the space in the second example) will both
                 use the icon for MP3 files.

                 Icons are not supported by all displays, so this may be ig-
                 nored.

     -I, --iconpath path
                 Sets the notification icon to the given file's icon (the icon
                 you would see in the Finder if you were looking at the file).

                 Icons are not supported by all displays, so this may be ig-
                 nored.

     --image path
                 Sets the notification icon to contents of the given image
                 file. As of Mac OS X 10.3, this file must be in PNG, JPEG,
                 TIFF, PICT, PDF, JPEG 2000, Adobe Photoshop, BMP, .ico, or
                 .icns format. If the image data is in a format Growl doesn't
                 recognize, the notification will still go through, and the
                 icon will be ignored.

                 Icons are not supported by all displays, so this may be ig-
                 nored anyway.

     -p, --priority priority
                 Sets the priority for the notification to an int or named key
                 (default is 0).

                 Priority is not supported by all displays, so this may be ig-
                 nored.

     -s, --sticky
                 Causes the notification to stick around until clicked.

                 Sticky notifications are not supported by all displays, so
                 this may be ignored.

     -d, --identifier
                 Sets the identifier for the notification. The identifier is
                 used for coalescing, which means multiple notifications with
                 the same identifer will use a single bubble, the latest noti-
                 fication taking precedence.

                 Coalescing is not supported by all displays, so this may be
                 ignored.

     -w, --wait  Causes growlnotify to wait until the notification is dis-
                 missed (either by clicking or timing out) before it returns.

     -H, --host  Sends the notification to a remote host instead of the local
                 computer.  This option requires the remote host being set up
                 to accept remote notifications.  The argument is the host to
                 send the notification to.

     -P, --password
                 Sets the password to be used for the remote notification.
                 This is necessary if the remote host requires a password for
                 remote notifications.

     growlnotify displays a notification using Growl. If -m isn't specified or
     is set to '-', the message is read from stdin.  If you don't redirect
     stdin (e.g. with the shell's | or < operators), growlnotify will be read-
     ing from the terminal, and you will need to send EOF (normally, ctrl-D)
     on an empty line to end the message.

     If -p is used then priority can be an int between -2 and 2 or can be a
     named key in the following list: Very Low, Moderate, Normal, High, Emer-
     gency.

EXAMPLES
           % growlnotify --help

     Displays this help file.

           % growlnotify --appIcon Xcode Build complete
           growlnotify has finished building
           ^D

     Displays a notification telling you that growlnotify has finished build-
     ing.

           growlnotify --appIcon Xcode Build complete -m 'growlnotify has
           finished building'

     The same as the previous one but suitable for embedding in a script (such
     as a Shell Script phase).

SEE ALSO
     stdin(4)

HISTORY
     First appeared as an example for Growl 0.5.  GrowlNotify 1.3 changed be-
     havior significantly. All the old methods (UDP, NSDNC, etc) of talking to
     Growl have been removed, replaced with GNTP (Growl Network Transport Pro-
     tocol).  Options relating directly to the old UDP system have been re-
     moved.  Progress option removed.

Darwin                           March 6, 2022                          Darwin
** dos style help (growlnotify /?)
Send a Growl notification to a local or remote host

growlnotify [/t:title] [/id:id] [/s:sticky] [/p:priority] [/i:icon]
            [/a:application] [/ai:icon] [/r:type] [/n:type]
            [/cu:callbackurl]
            [/host:host] [/port:port]
            [/pass:password] [/enc:algorithm] [/hash:algorithm]
            [/silent:nooutput]
            messagetext

  [/t:title]            The notification title.
                        Use \n to specify a line break. 
                        Use \\n for a literal '\n'.
                        Default: "growlnotify"

  [/id:id]              The notification id.
                        Default: ""

  [/s:sticky]           Indicates if the notification should be sticky.
                        Valid values: true|false
                        Default: false

  [/p:priority]         The notification priority.
                        Valid values: -2|-1|0|1|2
                        Default: 0

  [/i:icon]             The icon to show for the notification.
                        Must be a valid file type (png, jpg, gif, ico).
                        Can be any of the following:
                          - absolute url (http://domain/image.png)
                          - absolute file path (c:\temp\image.png)
                          - relative file path (.\folder\image.png) (relative 
                            file paths must start with a dot (.) and are 
                            relative to growlnotify's location
                        Note: Icons specified as urls will be passed as urls 
                              (links). Icons specified as local files (either 
                              absolute or relative) will be sent as binary 
                              data.
                        Default: no icon

  [/a:application]      The name of the application sending the notification.
                        The application must already be registered unless the
                        /r switch is included. The default 'growlnotify'
                        application does not need to be explicitly registered.
                        Default: growlnotify

  [/ai:appicon]			The icon of the application being registered.
						Only applicable if the /r switch is also passed.
                        Must be a valid file type (png, jpg, gif, ico).
                        Can be any of the following:
                          - absolute url (http://domain/image.png)
                          - absolute file path (c:\temp\image.png)
                          - relative file path (.\folder\image.png) (relative 
                            file paths must start with a dot (.) and are 
                            relative to growlnotify's location
                        Note: Icons specified as urls will be passed as urls 
                              (links). Icons specified as local files (either 
                              absolute or relative) will be sent as binary 
                              data.
                        Default: no icon

  [/r:type]             Register the application first.
                        'types' is a comma-separated list of the notification 
                        types to register.
                        Default: application not automatically registered
                        Examples:
                            /r:"Some Notification"
                            /r:"Notification One","Notification Two","Notification Three"

  [/n:type]             The notification name/type.
                        Default: "General Notification"

  [/cu:callbackurl]     A callback url (will be opened if the notification is 
                        clicked).
                        Default: no callback

  [/host:host]          The host address to send the notification to.
                        If any value other than 'localhost' or '127.0.0.1' is 
                        provided, the host is considered a remote host and the 
                        /pass switch must also be provided.
                        Default: localhost

  [/port:port]          The port to send the notification to.
                        Default: 23053

  [/pass:password]      The password required to send notifications.
                        A password is required to send a request to a remote 
                        host. If /host is specified and is any value other than
                        'localhost' or '127.0.0.1', then /pass is also 
                        required.
                        Default: no password

  [/enc:algorithm]      The encryption algorithm to use.
                        Valid values: NONE|DES|3DES|AES
                        If a value other than NONE is provided, the
                        /pass and /hash switches must also be included.
                        Default: NONE

  [/hash:algorithm]     The hashing algorithm to use.
                        Valid values: MD5|SHA1|SHA256|SHA512
                        This value is only used if the /pass switch is also
                        set.
                        Default: MD5

  [/silent:nooutput]	When run from the command line, indicates if response 
                        output should be suppressed or not.
                        Valid values: true|false
                        Default: false

  messagetext			The notification's text - Required
                        Use \n to specify a line break. 
                        Use \\n for a literal '\n'.

* examples

** ahk fragment
SyncUser = %PartnerName%
Application = Sync%SyncUser%
Title = "User Sync"
rNotif1 = "General Notification"
rNotif2 = "Sync Start Notification"
rNotif3 = "Sync Complete Notification"
rNotif4 = "Sync Failure Notification"
Nofif = "General Notification"
Message = "User %SyncUser% Script Registered in Growl."

Run growlnotify.exe /t:%Title% /s:false /p:2 /a:%Application% /r:%rNotif1%`,%rNotif2%`,%rNotif3%`,%rNotif4% /n:%Notif% %Message%

Don't know what the notifications mean, and no /r parameter is required
** what works
- ./growlnotify /a:ploooop  /r:"Sync Start Notificatizo" /n:"Sync Start Notificatizo" "test message"
It looks like the /n means this is the notification we want to invoke
/r will register the notification now
/n:FOO requires that /r:FOO happened in the past
thats why /r:FOO /n:FOO works right away
but /n:FOO won't work on its own unless /r:FOO was previously invoked
** can't find more displays
** displays are dlls, so would need to write and compile code
** why isn't it maintained now
** so we could make org-mode tasks produce notifications
   that was our quest, but it doesn't really look like that
   is what we wanted, we could 

** raw
#host:boo
#time:220306-215658
#pwd:/cygdrive/e/home/nick
215658 1 ~ $ "D:/G/Growl/growlnotify.exe" title "-a" "Emacs"
Bad arguments : An item with the same key has already been added.
220045 2 ~ $ "D:/G/Growl/growlnotify.exe" "splark" "-a" "Emacs Z"
Bad arguments : An item with the same key has already been added.
220217 3 ~ $ "D:/G/Growl/growlnotify.exe" -?
Notification sent successfully
Notification sent successfully

220238 4 ~ $ "D:/G/Growl/growlnotify.exe" -h
Notification sent successfully
Notification sent successfully

220251 5 ~ $ "D:/G/Growl/growlnotify.exe" -h
Notification sent successfully
Notification sent successfully

220254 6 ~ $ "D:/G/Growl/growlnotify.exe" -h
Notification sent successfully
Notification sent successfully

220257 7 ~ $ echo "hello world" | growlnotify -a TextEdit -d HelloWorld -t "The Title Here"
-bash: growlnotify: command not found
220401 8 ~ $ echo "hello world" | d:/G/Growl/growlnotify -a TextEdit -d HelloWorld -t "The Title Here"
Bad arguments : An item with the same key has already been added.
220417 9 ~ $ echo "hello world" | d:/G/Growl/growlnotify -a fart -d FartHelloWorld -t "The Fart Title Here"
Bad arguments : An item with the same key has already been added.
220445 10 ~ $ ^C
220508 10 ~ $ echo "hello world" | d:/G/Growl/growlnotify.com -a fart -d FartHelloWorld -t "The Fart Title Here"
Bad arguments : An item with the same key has already been added.
220556 11 ~ $ echo "hello world" | d:/G/Growl/growlnotify.com -a "fart" -d "FartHelloWorld" -t ""The Fart Title Here""
Bad arguments : An item with the same key has already been added.
220630 12 ~ $ cmd
Microsoft Windows [Version 10.0.17763.2565]
(c) 2018 Microsoft Corporation. All rights reserved.

E:\home\nick>echo "hello world" | d:/G/Growl/growlnotify -a fart -d FartHelloWorld -t "The Fart Title Here"
'd:' is not recognized as an internal or external command,
operable program or batch file.

E:\home\nick>echo "hello world" | d:\G\Growl\growlnotify -a fart -d FartHelloWorld -t "The Fart Title Here"
Bad arguments : An item with the same key has already been added.

E:\home\nick>echo "hello world" | d:\G\Growl\growlnotify -d FartHelloWorld -t "The Fart Title Here"
Bad arguments : An item with the same key has already been added.

E:\home\nick>echo "hello world" | d:\G\Growl\growlnotify -t "The Fart Title Here"
Bad arguments : An item with the same key has already been added.

E:\home\nick>echo "hello world" | d:\G\Growl\growlnotify
Invalid arguments. See /? for usage.

E:\home\nick>echo "hello world" | d:\G\Growl\growlnotify /?

Send a Growl notification to a local or remote host

growlnotify [/t:title] [/id:id] [/s:sticky] [/p:priority] [/i:icon]
            [/a:application] [/ai:icon] [/r:type] [/n:type]
            [/cu:callbackurl]
            [/host:host] [/port:port]
            [/pass:password] [/enc:algorithm] [/hash:algorithm]
            [/silent:nooutput]
            messagetext

  [/t:title]            The notification title.
                        Use \n to specify a line break.
                        Use \\n for a literal '\n'.
                        Default: "growlnotify"

  [/id:id]              The notification id.
                        Default: ""

  [/s:sticky]           Indicates if the notification should be sticky.
                        Valid values: true|false
                        Default: false

  [/p:priority]         The notification priority.
                        Valid values: -2|-1|0|1|2
                        Default: 0

  [/i:icon]             The icon to show for the notification.
                        Must be a valid file type (png, jpg, gif, ico).
                        Can be any of the following:
                          - absolute url (http://domain/image.png)
                          - absolute file path (c:\temp\image.png)
                          - relative file path (.\folder\image.png) (relative
                            file paths must start with a dot (.) and are
                            relative to growlnotify's location
                        Note: Icons specified as urls will be passed as urls
                              (links). Icons specified as local files (either
                              absolute or relative) will be sent as binary
                              data.
                        Default: no icon

  [/a:application]      The name of the application sending the notification.
                        The application must already be registered unless the
                        /r switch is included. The default 'growlnotify'
                        application does not need to be explicitly registered.
                        Default: growlnotify

  [/ai:appicon]                 The icon of the application being registered.
                                                Only applicable if the /r switch is also passed.
                        Must be a valid file type (png, jpg, gif, ico).
                        Can be any of the following:
                          - absolute url (http://domain/image.png)

  [/enc:algorithm]      The encryption algorithm to use.
                        Valid values: NONE|DES|3DES|AES
                        If a value other than NONE is provided, the
                        /pass and /hash switches must also be included.
                        Default: NONE

  [/hash:algorithm]     The hashing algorithm to use.
                        Valid values: MD5|SHA1|SHA256|SHA512
                        This value is only used if the /pass switch is also
                        set.
                        Default: MD5

  [/silent:nooutput]    When run from the command line, indicates if response
                        output should be suppressed or not.
                        Valid values: true|false
                        Default: false

  messagetext                   The notification's text - Required
                        Use \n to specify a line break.
                        Use \\n for a literal '\n'.


E:\home\nick>echo "hello world" | d:\G\Growl\growlnotify /a fart /d FartHelloWorld /t "The Fart Title Here"
Bad arguments : Index was outside the bounds of the array.

E:\home\nick>echo "hello world" | d:\G\Growl\growlnotify /a "fart" /d "FartHelloWorld" /t "The Fart Title Here"
Bad arguments : Index was outside the bounds of the array.

E:\home\nick>echo "hello world" | d:\G\Growl\growlnotify /a:fart /d:FartHelloWorld" /t "The Fart Title Here"
Bad arguments : An item with the same key has already been added.

E:\home\nick>echo "hello world" | d:\G\Growl\growlnotify /a:fart /d:FartHelloWorld" /t:TheFartTitleHere
Missing 'messagetext' argument. See /? for usage

E:\home\nick>echo "hello world" | d:\G\Growl\growlnotify /a:fart /d:FartHelloWorld /t:TheFartTitleHere
Missing 'messagetext' argument. See /? for usage

E:\home\nick>d:\G\Growl\growlnotify /a:fart /d:FartHelloWorld /t:TheFartTitleHere look
Notification failed: 401 - Application not registered


E:\home\nick>
E:\home\nick>d:\G\Growl\growlnotify /r:fart /d:FartHelloWorld /t:TheFartTitleHere look
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /a:fart look
Notification failed: 401 - Application not registered


E:\home\nick>d:\G\Growl\growlnotify /a:fart look
Notification failed: 401 - Application not registered


E:\home\nick>d:\G\Growl\growlnotify /r:fart look
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /r:fart /t:tit
Missing 'messagetext' argument. See /? for usage

E:\home\nick>d:\G\Growl\growlnotify /r:fart /t:tit smash
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /a:fart /t:tit smash
Notification failed: 401 - Application not registered


E:\home\nick>d:\G\Growl\growlnotify /r:faart /t:tit smash
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /t:tit smash
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /t:tit smash
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /t:tit /n:smurf smash
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /r:ulp /t:tit /n:smurf smash
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /r:ulp /n:smurf smash
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /r:ulp smash
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /r:"ulp" smash
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /a:ulp /r:"ulp" smash
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /a:ulp /r:"ulp" smash
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /a:ulp  smash
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /r:ulp  smash
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /r:ulp  /n:shit smash
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /a:ulp  /n:shit smash
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /v
Bad arguments : Index was outside the bounds of the array.

E:\home\nick>d:\G\Growl\growlnotify -v
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify -h
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /h
Bad arguments : Index was outside the bounds of the array.

E:\home\nick>d:\G\Growl\growlnotify /?

Send a Growl notification to a local or remote host

growlnotify [/t:title] [/id:id] [/s:sticky] [/p:priority] [/i:icon]
            [/a:application] [/ai:icon] [/r:type] [/n:type]
            [/cu:callbackurl]
            [/host:host] [/port:port]
            [/pass:password] [/enc:algorithm] [/hash:algorithm]
            [/silent:nooutput]
            messagetext

  [/t:title]            The notification title.
                        Use \n to specify a line break.
                        Use \\n for a literal '\n'.
                        Default: "growlnotify"

  [/id:id]              The notification id.
                        Default: ""

  [/s:sticky]           Indicates if the notification should be sticky.
                        Valid values: true|false
                        Default: false

  [/p:priority]         The notification priority.
                        Valid values: -2|-1|0|1|2
                        Default: 0

  [/i:icon]             The icon to show for the notification.
                        Must be a valid file type (png, jpg, gif, ico).
                        Can be any of the following:
                          - absolute url (http://domain/image.png)
                          - absolute file path (c:\temp\image.png)
                          - relative file path (.\folder\image.png) (relative
                            file paths must start with a dot (.) and are
                            relative to growlnotify's location
                        Note: Icons specified as urls will be passed as urls
                              (links). Icons specified as local files (either
                              absolute or relative) will be sent as binary
                              data.
                        Default: no icon

  [/a:application]      The name of the application sending the notification.
                        The application must already be registered unless the
                        /r switch is included. The default 'growlnotify'
                        application does not need to be explicitly registered.
                        Default: growlnotify

  [/ai:appicon]                 The icon of the application being registered.
                                                Only applicable if the /r switch is also passed.
                        Must be a valid file type (png, jpg, gif, ico).
                        Can be any of the following:
                          - absolute url (http://domain/image.png)
                          - absolute file path (c:\temp\image.png)
                          - relative file path (.\folder\image.png) (relative
                            file paths must start with a dot (.) and are
                            relative to growlnotify's location
                        Note: Icons specified as urls will be passed as urls
                              (links). Icons specified as local files (either
                              absolute or relative) will be sent as binary
                              data.
                        Default: no icon

  [/r:type]             Register the application first.
                        'types' is a comma-separated list of the notification
                        types to register.
                        Default: application not automatically registered
                        Examples:
                            /r:"Some Notification"
                            /r:"Notification One","Notification Two","Notification Three"

  [/n:type]             The notification name/type.
                        Default: "General Notification"

  [/cu:callbackurl]     A callback url (will be opened if the notification is
                        clicked).
                        Default: no callback

  [/host:host]          The host address to send the notification to.
                        If any value other than 'localhost' or '127.0.0.1' is
                        provided, the host is considered a remote host and the
                        /pass switch must also be provided.
                        Default: localhost

  [/port:port]          The port to send the notification to.
                        Default: 23053

  [/pass:password]      The password required to send notifications.
                        A password is required to send a request to a remote
                        host. If /host is specified and is any value other than
                        'localhost' or '127.0.0.1', then /pass is also
                        required.
                        Default: no password

  [/enc:algorithm]      The encryption algorithm to use.
                        Valid values: NONE|DES|3DES|AES
                        If a value other than NONE is provided, the
                        /pass and /hash switches must also be included.
                        Default: NONE

  [/hash:algorithm]     The hashing algorithm to use.
                        Valid values: MD5|SHA1|SHA256|SHA512
                        This value is only used if the /pass switch is also
                        set.
                        Default: MD5

  [/silent:nooutput]    When run from the command line, indicates if response
                        output should be suppressed or not.
                        Valid values: true|false
                        Default: false

  messagetext                   The notification's text - Required
                        Use \n to specify a line break.
                        Use \\n for a literal '\n'.


E:\home\nick>d:\G\Growl\growlnotify /a ulp  /n shit smash
Bad arguments : Index was outside the bounds of the array.

E:\home\nick>d:\G\Growl\growlnotify /a "ulp"  /n "shit" smash
Bad arguments : Index was outside the bounds of the array.

E:\home\nick>d:\G\Growl\growlnotify /a "ulp"  /n "shit"
Bad arguments : Index was outside the bounds of the array.

E:\home\nick>d:\G\Growl\growlnotify "/a:ulp"  "/n:shit"
Missing 'messagetext' argument. See /? for usage

E:\home\nick>d:\G\Growl\growlnotify "/a:ulp"  "/n:shit" "frap"
Notification failed: 402 - Notification type not registered


E:\home\nick>
E:\home\nick>d:\G\Growl\growlnotify "test message"
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /a:shoooo /r:a,b,c,d "test message"
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>
E:\home\nick>d:\G\Growl\growlnotify /a:shoooo /r:"General Notification" "test message"
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /a:shoooo /r:"General Notification" "test message"
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /a:shoooo /r:"General Notification" "test message blah blah"
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /r:"General Notification" "test message"
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /a:twat /r:"General Notification" "test message"
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /a:twat /r:"General Notification" "test message"
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /r:"General Notification" "test message"
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /a:ploooop /r:"General Notification" "test message"
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /a:ploooop /r:"General Notificatio" "test message"
Notification sent successfully
Notification failed: 402 - Notification type not registered


E:\home\nick>d:\G\Growl\growlnotify /r:"General Notification" "test message"
Notification sent successfully
Notification sent successfully


E:\home\nick>d:\G\Growl\growlnotify /a:ploooop  "test message"
Notification failed: 402 - Notification type not registered


* growl sounds
https://groups.google.com/g/growl-for-windows/c/TWM_UxyUUeM?hl=en
