(add-variable-watcher 'org-agenda-files 'org-agenda-files-watcher-2)
(add-variable-watcher 'org-agenda-files 'org-agenda-files-watcher)
(remove-variable-watcher 'org-agenda-files 'org-agenda-files-watcher-2)
(remove-variable-watcher 'org-agenda-files 'org-agenda-files-watcher)
(defun org-agenda-files-watcher (symbol newval operation where)
  (message "1")
  (debug)
  )
(defun org-agenda-files-watcher-2 (symbol newval operation where)
  (message "2")
  (debug)
  )
