;; alt-hyper key bindings

;(def-key global-map (kbd "A-H-q") 'nil)
;(def-key global-map (kbd "A-H-w") 'nil)
;(def-key global-map (kbd "A-H-e") 'nil)
;(def-key global-map (kbd "A-H-r") 'nil)
;(def-key global-map (kbd "A-H-a") 'nil)
;(def-key global-map (kbd "A-H-s") 'nil)
;(def-key global-map (kbd "A-H-d") 'nil)
;(def-key global-map (kbd "A-H-f") 'nil)
;(def-key global-map (kbd "A-H-z") 'nil)
;(def-key global-map (kbd "A-H-x") 'nil)
;(def-key global-map (kbd "A-H-c") 'nil)
;(def-key global-map (kbd "A-H-v") 'nil)
;(def-key global-map (kbd "A-H-1") 'nil)
;(def-key global-map (kbd "A-H-2") 'nil)
;(def-key global-map (kbd "A-H-3") 'nil)
;(def-key global-map (kbd "A-H-4") 'nil)

;(def-key global-map (kbd "A-H-/") 'nil)
;(def-key global-map (kbd "A-H-'") 'nil)
;(def-key global-map (kbd "A-H-]") 'nil)
;(def-key global-map (kbd "A-H-[") 'nil)
;(def-key global-map (kbd "A-H-#") 'nil)
;(def-key global-map (kbd "A-H-;") 'nil)
;(def-key global-map (kbd "A-H-=") 'nil)
;(def-key global-map (kbd "A-H--") 'nil)

;(def-key global-map (kbd "<A-H-delete>") 'nil)
;(def-key global-map (kbd "<A-H-end>") 'nil)
;(def-key global-map (kbd "<A-H-insert>") 'nil)
;(def-key global-map (kbd "<A-H-home>") 'nil)
;(def-key global-map (kbd "<A-H-prior>") 'nil)
;(def-key global-map (kbd "<A-H-next>") 'nil)


