;; alt-ctrl key bindings

;(def-key global-map (kbd "A-C-q") 'nil)
;(def-key global-map (kbd "A-C-w") 'nil)
;(def-key global-map (kbd "A-C-e") 'nil)
;(def-key global-map (kbd "A-C-r") 'nil)
;(def-key global-map (kbd "A-C-a") 'nil)
;(def-key global-map (kbd "A-C-s") 'nil)
;(def-key global-map (kbd "A-C-d") 'nil)
;(def-key global-map (kbd "A-C-f") 'nil)
;(def-key global-map (kbd "A-C-z") 'nil)
;(def-key global-map (kbd "A-C-x") 'nil)
;(def-key global-map (kbd "A-C-c") 'nil)
;(def-key global-map (kbd "A-C-v") 'nil)
;(def-key global-map (kbd "A-C-1") 'nil)
;(def-key global-map (kbd "A-C-2") 'nil)
;(def-key global-map (kbd "A-C-3") 'nil)
;(def-key global-map (kbd "A-C-4") 'nil)

;(def-key global-map (kbd "A-C-/") 'nil)
;(def-key global-map (kbd "A-C-'") 'nil)
;(def-key global-map (kbd "A-C-]") 'nil)
;(def-key global-map (kbd "A-C-[") 'nil)
;(def-key global-map (kbd "A-C-#") 'nil)
;(def-key global-map (kbd "A-C-;") 'nil)
;(def-key global-map (kbd "A-C-=") 'nil)
;(def-key global-map (kbd "A-C--") 'nil)

;(def-key global-map (kbd "<A-C-delete>") 'nil)
;(def-key global-map (kbd "<A-C-end>") 'nil)
;(def-key global-map (kbd "<A-C-insert>") 'nil)
;(def-key global-map (kbd "<A-C-home>") 'nil)
;(def-key global-map (kbd "<A-C-prior>") 'nil)
;(def-key global-map (kbd "<A-C-next>") 'nil)


