;; alt-super key bindings

;(define-key global-map (kbd "A-s-q") 'nil)
;(define-key global-map (kbd "A-s-w") 'nil)
;(define-key global-map (kbd "A-s-e") 'nil)
;(define-key global-map (kbd "A-s-r") 'nil)
;(define-key global-map (kbd "A-s-a") 'nil)
;(define-key global-map (kbd "A-s-s") 'nil)
;(define-key global-map (kbd "A-s-d") 'nil)
;(define-key global-map (kbd "A-s-f") 'nil)
;(define-key global-map (kbd "A-s-z") 'nil)
;(define-key global-map (kbd "A-s-x") 'nil)
;(define-key global-map (kbd "A-s-c") 'nil)
;(define-key global-map (kbd "A-s-v") 'nil)
;(define-key global-map (kbd "A-s-1") 'nil)
;(define-key global-map (kbd "A-s-2") 'nil)
;(define-key global-map (kbd "A-s-3") 'nil)
;(define-key global-map (kbd "A-s-4") 'nil)

;(define-key global-map (kbd "A-s-/") 'nil)
;(define-key global-map (kbd "A-s-'") 'nil)
;(define-key global-map (kbd "A-s-]") 'nil)
;(define-key global-map (kbd "A-s-[") 'nil)
;(define-key global-map (kbd "A-s-#") 'nil)
;(define-key global-map (kbd "A-s-;") 'nil)
;(define-key global-map (kbd "A-s-=") 'nil)
;(define-key global-map (kbd "A-s--") 'nil)

;(define-key global-map (kbd "<A-s-delete>") 'nil)
;(define-key global-map (kbd "<A-s-end>") 'nil)
;(define-key global-map (kbd "<A-s-insert>") 'nil)
;(define-key global-map (kbd "<A-s-home>") 'nil)
;(define-key global-map (kbd "<A-s-prior>") 'nil)
;(define-key global-map (kbd "<A-s-next>") 'nil)


