;; ctrl-super key bindings

;(def-key global-map (kbd "C-s-q") 'nil)
;(def-key global-map (kbd "C-s-w") 'nil)
;(def-key global-map (kbd "C-s-e") 'nil)
;(def-key global-map (kbd "C-s-r") 'nil)
;(def-key global-map (kbd "C-s-a") 'nil)
;(def-key global-map (kbd "C-s-s") 'nil)
;(def-key global-map (kbd "C-s-d") 'nil)
;(def-key global-map (kbd "C-s-f") 'nil)
;(def-key global-map (kbd "C-s-z") 'nil)
;(def-key global-map (kbd "C-s-x") 'nil)
;(def-key global-map (kbd "C-s-c") 'nil)
;(def-key global-map (kbd "C-s-v") 'nil)
;(def-key global-map (kbd "C-s-1") 'nil)
;(def-key global-map (kbd "C-s-2") 'nil)
;(def-key global-map (kbd "C-s-3") 'nil)
;(def-key global-map (kbd "C-s-4") 'nil)

;(def-key global-map (kbd "C-s-/") 'nil)
;(def-key global-map (kbd "C-s-'") 'nil)
;(def-key global-map (kbd "C-s-]") 'nil)
;(def-key global-map (kbd "C-s-[") 'nil)
;(def-key global-map (kbd "C-s-#") 'nil)
;(def-key global-map (kbd "C-s-;") 'nil)
;(def-key global-map (kbd "C-s-=") 'nil)
;(def-key global-map (kbd "C-s--") 'nil)

;(def-key global-map (kbd "<C-s-delete>") 'nil)
;(def-key global-map (kbd "<C-s-end>") 'nil)
;(def-key global-map (kbd "<C-s-insert>") 'nil)
;(def-key global-map (kbd "<C-s-home>") 'nil)
;(def-key global-map (kbd "<C-s-prior>") 'nil)
;(def-key global-map (kbd "<C-s-next>") 'nil)


