;; meta-super key bindings

;(define-key global-map (kbd "M-s-q") 'nil)
;(define-key global-map (kbd "M-s-w") 'nil)
;(define-key global-map (kbd "M-s-e") 'nil)
;(define-key global-map (kbd "M-s-r") 'nil)
;(define-key global-map (kbd "M-s-a") 'nil)
;(define-key global-map (kbd "M-s-s") 'nil)
;(define-key global-map (kbd "M-s-d") 'nil)
;(define-key global-map (kbd "M-s-f") 'nil)
;(define-key global-map (kbd "M-s-z") 'nil)
;(define-key global-map (kbd "M-s-x") 'nil)
;(define-key global-map (kbd "M-s-c") 'nil)
;(define-key global-map (kbd "M-s-v") 'nil)
;(define-key global-map (kbd "M-s-1") 'nil)
;(define-key global-map (kbd "M-s-2") 'nil)
;(define-key global-map (kbd "M-s-3") 'nil)
;(define-key global-map (kbd "M-s-4") 'nil)

;(define-key global-map (kbd "M-s-/") 'nil)
;(define-key global-map (kbd "M-s-'") 'nil)
;(define-key global-map (kbd "M-s-]") 'nil)
;(define-key global-map (kbd "M-s-[") 'nil)
;(define-key global-map (kbd "M-s-#") 'nil)
;(define-key global-map (kbd "M-s-;") 'nil)
;(define-key global-map (kbd "M-s-=") 'nil)
;(define-key global-map (kbd "M-s--") 'nil)

;(define-key global-map (kbd "<M-s-delete>") 'nil)
;(define-key global-map (kbd "<M-s-end>") 'nil)
;(define-key global-map (kbd "<M-s-insert>") 'nil)
;(define-key global-map (kbd "<M-s-home>") 'nil)
;(define-key global-map (kbd "<M-s-prior>") 'nil)
;(define-key global-map (kbd "<M-s-next>") 'nil)


